### ISSUE TITLE
Some ontologies are incorrectly flagged as having a non-resolvable version IRI

### ISSUE THREAD

**Issue by gouttegd** [OBOFoundry/OBO-Dashboard#103]
In the last release of the OBO Dashboard, several ontologies that used to pass the “versioning” check now fail it, the error being that the “version IRI does not resolve” – even though those ontologies do in fact have a version IRI that resolves to a release artefact.

Example with FBbt: version IRI in the latest release is `http://purl.obolibrary.org/obo/fbbt/releases/2023-10-18/fbbt.owl`. That correctly resolves to the OWL artefact of the latest release (it resolves to the same product as `http://purl.obolibrary.org/obo/fbbt.owl` in fact).

Same for Mondo: version IRI in the latest release is `http://purl.obolibrary.org/obo/mondo/releases/2023-09-12/mondo.owl`, this resolves to a working product as well.

**Comment by matentzn** [comment]
Related maybe? https://github.com/OBOFoundry/OBO-Dashboard/issues/104

**Comment by sbello** [comment]
The MP has the same issue, I had fixed all the errors according to the last release of the dashboard but the new one has the MP with a version issue when nothing about the version changed.

**Comment by anitacaron** [comment]
I couldn't replicate the issue locally. There may have been an internet interruption during the pipeline. I'll run a new release by the end of this week, and I'll make sure to verify this.

**Comment by anitacaron** [comment]
The new dashboard release shows that the issue was fixed for both cases listed here.

![Screenshot 2024-01-08 at 10 11 04](https://github.com/OBOFoundry/OBO-Dashboard/assets/2208124/5347c477-a8d8-42da-a89d-e0b2839d2a34)
![Screenshot 2024-01-08 at 10 11 31](https://github.com/OBOFoundry/OBO-Dashboard/assets/2208124/6519ab19-303d-48c7-ba82-13ec3f3b9526)
