### ISSUE TITLE
Specific problems should link to specific fixes

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBO-Dashboard#12]
Each check page has a "Fixes" section, but we should clearly link from `dashboard.html` to the specific fix required.

This will require reworking `dashboard.yml` to have a list of problems for each principle, each of which will have a link to the fix, a comment, and maybe a file link.

**Comment by anitacaron** [comment]
This was done by PR https://github.com/OBOFoundry/OBO-Dashboard/pull/84.
