### ISSUE TITLE
How frequently is this run on the suite of OBO Foundry ontologies?

### ISSUE THREAD

**Issue by ddooley** [OBOFoundry/OBO-Dashboard#121]
Is this updated on a periodic basis?  
Do I ask for the dashboard to update a particular ontology like ONS? (https://github.com/enpadasi/Ontology-for-Nutritional-Studies/blob/master/ons.owl) 
If so please regen that report, thanks!  ONS has just launched a revamp, and so I think it would start showing up properly in the dashboard.  Much obliged!

**Comment by anitacaron** [comment]
Hi @ddooley, I run the dashboard monthly by the end of the month. I always announce new dashboard releases on the channel #dashboard in the obo-community Slack workspace.

**Comment by ddooley** [comment]
Ok, thanks!
