### ISSUE TITLE
Eliminate ROBOT operations from Python scripts, in favour of XML operations

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBO-Dashboard#14]
First, some history. We chose Python to implement these checks because it's readable by the widest portion of the OBO community, and good for the quick pace of development we wanted. Since we also wanted to work with OWL files, we implemented a bunch of checks using ROBOT's new [Python interface](http://robot.obolibrary.org/python), which involves starting a Java process for ROBOT and controlling it from Python. However for the larger ontologies, such as NCBITaxon and PR, this required too much memory. We ended up implementing various `big_*` alternative functions that assumed the input was RDF/XML from OWLAPI then looked for the bits and pieces of XML that we needed.

For example, to get the version IRI we can call ROBOT from Python, or we can just just look in the first bunch of lines of an RDF/XML file then exit:

https://github.com/OBOFoundry/OBO-Dashboard/blob/master/util/dashboard/dash_utils.py#L151
https://github.com/OBOFoundry/OBO-Dashboard/blob/master/util/dashboard/dash_utils.py#L163

It turns out we always have RDF/XML from OWLAPI ([because of how we build base files](https://github.com/OBOFoundry/OBO-Dashboard/blob/master/Makefile#L104)), and we've been able to do everything we need by looking at the XML.

So we don't actually need all those ROBOT calls from Python. They can be eliminated in favour of the XML processing code. We still need ROBOT to run `robot report` from the command-line, but not from Python.

**Comment by cmungall** [comment]
is there any advantage in switching?

**Comment by jamesaoverton** [comment]
If we're using base files provided by projects (and we should) then that breaks the assumption about consistent XML that I was basing this on. So I'll close.

In retrospect, I wish we'd used SPARQL to answer all questions about the ontology file content, and only used Python to process the resulting tables.
