### ISSUE TITLE
mirnao was passing "Format" without a valid OWL file

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBO-Dashboard#16]
I just marked mirnao as obsolete https://github.com/OBOFoundry/OBOFoundry.github.io/pull/789, which means we won't bother running the dashboard checks any more.

However the Format check was passing even though the primary PURL is a 404, so something went wrong:

http://obo-dashboard-test.ontodev.com/mirnao/dashboard.html
http://purl.obolibrary.org/obo/mirnao.owl

**Comment by cmungall** [comment]
I can't seem to reproduce this:

```
$ make dashboard/mirnao/dashboard.html
java -Xmx10G -jar build/robot.jar merge --input-iri http://purl.obolibrary.org/obo/mirnao.owl \
         remove --base-iri MIRNAO --axioms external -p false --output build/ontologies/mirnao.owl
org.semanticweb.owlapi.io.OWLOntologyCreationIOException: http://mirna-ontology.googlecode.com/svn/trunk/src/ontology/mirnao.owl
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make: *** [build/ontologies/mirnao.owl] Error 1
```

in any case, @wdduncan is adding a filter to the creation of ontologies.txt to remove obsolete ontologies from the set tested
