### ISSUE TITLE
Enable Travis CI on this repo

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBO-Dashboard#17]
Travis should build the main table from scratch for a few ontologies:

```
ONTS="bfo obi eco" make all
```

I don't really care which ontologies, but I want Travis to run this test quickly and reliably.

**Comment by jamesaoverton** [comment]
When it's working, please add this badge to the README:

```
[![Build Status](https://travis-ci.org/OBOFoundry/OBO-Dashboard.svg?branch=master)](https://travis-ci.org/OBOFoundry/OBO-Dashboard)
```

**Comment by beckyjackson** [comment]
The travis build is passing and I've added the badge to the README

**Comment by jamesaoverton** [comment]
Thanks!
