### ISSUE TITLE
error encountered for dideo when running make all

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBO-Dashboard#19]
I tried to build the dashboard for all ontologies. It failed on `dieo`:
```
Checking dideo
Running ROBOT report on dideo...
See dashboard/dideo/robot_report.tsv for details

Saving results to dashboard/dideo/dashboard.yml
python3 util/create_report_html.py dashboard/dideo/robot_report.tsv dependencies/obo_context.jsonld util/templates/report.html.jinja2 "ROBOT Report - dideo" dashboard/dideo/robot_report.html
python3 util/create_report_html.py dashboard/dideo/fp3.tsv dependencies/obo_context.jsonld util/templates/report.html.jinja2 "IRI Report - dideo" dashboard/dideo/fp3.html
python3 util/create_report_html.py dashboard/dideo/fp7.tsv dependencies/obo_context.jsonld util/templates/report.html.jinja2 "Relations Report - dideo" dashboard/dideo/fp7.html
python3 util/create_ontology_html.py dashboard/dideo/dashboard.yml util/templates/ontology.html.jinja2 dashboard/dideo/dashboard.html
java -Xmx10G -jar build/robot.jar merge --input-iri http://purl.obolibrary.org/obo/dinto.owl \
	 remove --base-iri DINTO --axioms external -p false --output build/ontologies/dinto.owl
[Fatal Error] :9:3: The element type "p" must be terminated by the matching end-tag "</p>".
org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing http://purl.obolibrary.org/obo/dinto.owl
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser@4d666b41
2) org.semanticweb.owlapi.owlxml.parser.OWLXMLParser@27e32fe4
3) org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxOWLParser@781a9412
4) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RioTurtleDocumentFormatFactory@95fd655c
5) org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxOntologyParser@1dab9dd6
6) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.NQuadsDocumentFormatFactory@6f9c39ad
7) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFJsonDocumentFormatFactory@cd748dc3
8) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.TrigDocumentFormatFactory@27e81c
9) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.NTriplesDocumentFormatFactory@937ecd36
10) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFJsonLDDocumentFormatFactory@dcacc47d
11) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory@3bf24493
12) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.N3DocumentFormatFactory@9a5
13) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RioRDFXMLDocumentFormatFactory@69b9a3bc
14) org.semanticweb.owlapi.rdf.turtle.parser.TurtleOntologyParser@393881f0
15) org.semanticweb.owlapi.rio.RioTrixParserFactory$TrixParserImpl : org.semanticweb.owlapi.formats.TrixDocumentFormatFactory@27e82d
16) org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@4f186450
17) org.semanticweb.owlapi.krss2.parser.KRSS2OWLParser@7c455e96
18) org.semanticweb.owlapi.rio.RioParserImpl : org.semanticweb.owlapi.formats.RDFaDocumentFormatFactory@264e8d
```

**Comment by cmungall** [comment]
I think it's correct behavior to hard fail fast if an ontology can't resolve. Or we could have it catch the error and report a failure... but we'd have to distinguish between a genuinely unresolvable ontology and a network failure.

This will be resolved when dinto is marked inactive/obsolete:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/208

@beckyjackson how did you manage this before, did you manually exclude some ontologies like dinto from the run?

**Comment by nlharris** [comment]
> This will be resolved when dinto is marked inactive/obsolete:
OBOFoundry/OBOFoundry.github.io#208

Maybe this PR will fix that? (I'm still not sure whether there's anything additional required to mark an ontology inactive/obsolete).
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1195

**Comment by wdduncan** [comment]
When I run `make all`, I still receive the error.  
However, I can run `make dideo` just fine.

**Comment by jamesaoverton** [comment]
It will take more work to make the system run without some babysitting. The first place I would improve is fetching/caching all the OWL files first with `curl` instead of with ROBOT here: https://github.com/OBOFoundry/OBO-Dashboard/blob/master/Makefile#L101

As described in #14, the special handling of large ontologies was a mistake, in hindsight.

**Comment by wdduncan** [comment]
@jamesaoverton @cmungall 
The purl for DINTO http://purl.obolibrary.org/obo/dinto.owl redirects to a github repo; not an ontology file.  
Which variable is used to specify that the ontology purl is broken?

**Comment by matentzn** [comment]
Good catch. Odd one.

![image](https://user-images.githubusercontent.com/7070631/80755798-1f6fb500-8b3a-11ea-864e-3d698dff0305.png)

Not sure you can do much other then an issue in their repo

**Comment by jamesaoverton** [comment]
They don't have an OBO PURL configuration: https://github.com/OBOFoundry/purl.obolibrary.org/issues/14

It was recently marked obsolete, but something isn't right: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1195

**Comment by jamesaoverton** [comment]
DINTO is obsolete. This should fix that: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1202

**Comment by wdduncan** [comment]
OBOFoundry updated after PR.
