### ISSUE TITLE
Add ability to run dashboard over a new ontology

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBO-Dashboard#2]
In order to make commenting about new ontology requests less arbitrary and ad-hoc it would be fantastic to make it easy for either submitter or obo-ops to run the dashboard over the new ontology.

The input would be the metadata yaml plus a URL to download the ontology.

I think the implementation would be in 2 parts:

 1. Add a Dockerfile to this repo
 2. Add a target to the Makefile for making a 'minidash.html' that would make just for the new ontology

I'm aware Docker is hard for some to run but I think it may be the easiest path. We could consider some kind of server/service to do this but this is more work.

**Comment by jamesaoverton** [comment]
I agree with the goal. What do you think about adding the Dashboard stuff to ODK somehow?

**Comment by kltm** [comment]
As well, if one was okay with a different output format, forking or branching a repo and using travis as a runner to get the data is an option. (We experimented with a similar setup for GAFs at one point.)

**Comment by cmungall** [comment]
I think making as part of ODK is a good suggestion. Also takes the responsibility off you at Becky 😄 

Seth - currently each ontology repo has a single travis make target, typically "make test". We *could* make this part of make test but I worry that this may make the test cycle too long

**Comment by jamesaoverton** [comment]
I was thinking of keeping the dashboard stuff in its own repo here, and pulling it into ODK like you pull DOS-DP. We (all of us) can make whatever adjustments here that ODK needs. These scripts just need Python and ROBOT, so ODK has almost everything already.

**Comment by anitacaron** [comment]
To update this issue, there's a dedicated dashboard for new ontology requests https://github.com/OBOFoundry/obo-nor.github.io
