### ISSUE TITLE
"i" for ROBOT report shows "{0} info messages" on hover

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBO-Dashboard#32]
The "ROBOT report" cell for the "trans" ontology shows a blue "i", which, when you hover over it, says "{0} info messages".
![Screen Shot 2021-02-18 at 10 13 43 PM](https://user-images.githubusercontent.com/348704/108536339-36ca8b00-7291-11eb-9cfa-0d8caee24752.png)

**Comment by matentzn** [comment]
Thanks for the report! The reason is that trans has exactly one info message in the ROBOT report! But this is not very clear in the mouse over. Next time we iterate over the dashboard, we will make sure that. the message is more meaningful. Thank you.
