### ISSUE TITLE
excessive ROBOT report output for GO

### ISSUE THREAD

**Issue by balhoff** [OBOFoundry/OBO-Dashboard#35]
There are a lot of ROBOT report issues for GO on the dashboard that seem mistaken: http://dashboard.obofoundry.org/dashboard/go/robot_report.html

Most acute: how can we avoid errors for missing labels for external terms?

**Comment by matentzn** [comment]
@jamesaoverton, one way we could deal with this issue fast is to do the filtering on the Dashboard end. That way I could make a lot of people, like @balhoff, happy tomorrow; We still need to solve the issue at ROBOT level but I wont have time to deal with it unfortunately any time very soon :(

**Comment by matentzn** [comment]
@balhoff thanks for reporting!

**Comment by jamesaoverton** [comment]
@matentzn Filtering the ROBOT report for the Dashboard makes sense. I have no objections.

**Comment by matentzn** [comment]
This will be fixed on report level in this PR, so closing here.
https://github.com/ontodev/robot/pull/872
