### ISSUE TITLE
Hp website does not resolve 

### ISSUE THREAD

**Issue by drseb** [OBOFoundry/OBO-Dashboard#38]
Can you please explain how the „website resolve status“ is obtained? Hpo website is a Redirect currently, but current homepage at jax is online. So I am wondering how we can solve the situation.

**Comment by matentzn** [comment]
I am sure its just a bug :) Thanks for reporting! I will see that I fix this soon!

**Comment by matentzn** [comment]
closing in favour of https://github.com/OBOFoundry/OBO-Dashboard/issues/7
