### ISSUE TITLE
Use of http://purl.org/dc/elements/1.1/ vs http://purl.org/dc/terms/ for ontology title and description

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBO-Dashboard#43]
I noticed that the dashboard fails PR for both a missing title and a missing description, both of which are present in the OWL file header:

<terms:title rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PRotein Ontology</terms:title>

<terms:description rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The PRotein Ontology (PRO) formally defines taxon-specific and taxon-neutral protein-related entities in three major areas: proteins related by evolution; proteins produced from a given gene; and protein-containing complexes.</terms:description>

Upon checking, it seems that the dashboard is looking for dc::title and dc:description, while PR has specified terms:title and terms:description. I looked into the referenced document (https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) and discovered that we are actually using the recommended version, while the dashboard is looking for the 'old' version. From that document: 

"While the /elements/1.1/ namespace will be supported indefinitely, DCMI gently encourages use of the /terms/ namespace."

I therefore suggest that the dashboard allows for both.

**Comment by matentzn** [comment]
Thank you @nataled 

See my previous comments about this:
https://github.com/ontodev/robot/issues/741
https://github.com/information-artifact-ontology/ontology-metadata/issues/54

ha, its great the dashboard is bringing this up again - previously no one seemed to care :).

My personal take is this: I will back any attempt to _unify our ontology metadata_. So despite the dominance of the /elements/1.1/ namespace across obo ontologies for historical reasons, if people decide they want to for the more modern one instead (`terms`) I would greatly prefer that to allowing both. My only concern is that many ontologies have _just_ gotten their boxes green on dashboard (this check has been around for years), and it may annoy them to get them red again when we, semi-randomly from their perspective change from dce to terms. However, in my long term vision, we need to make things easier for end-users that do not know what dce and dcterms is - they should be able to query ontologies in a unified way, not having to keep lists of alternative properties in mind.

In any case, lets keep the debate raging!

**Comment by matentzn** [comment]
And, I was not even aware of this discussion:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/540

@cmungall thx

**Comment by nataled** [comment]
I share the concern about green to red. I'd say this could be phased in. For now, allow both as green. Once it is fully decided which version to use (like, "if in elements, always use that one" or "only use terms, ever"), then warn if using the now-"wrong" version. After some time, change that warn back to error.

**Comment by matentzn** [comment]
Closing this here, as this is being fixed in ROBOT: https://github.com/ontodev/robot/pull/863
