### ISSUE TITLE
multiple_equivalent_classes error without any actual equivalent classes

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBO-Dashboard#44]
Perusing the PR report, I see that there are a number of multiple_equivalent_classes errors. Unfortunately, such reports are almost useless (at least in my case) because there is no indication of which classes are equivalent. Here is an example:

<pre>
 9 | ERROR | multiple_equivalent_classes | cytochrome c oxidase 7B (mouse) | owl:equivalentClass | 41696da4-dd43-45ae-b681-91644ca5a5dcgenid99168
10 | ERROR | multiple_equivalent_classes | cytochrome c oxidase 7B (mouse) | owl:equivalentClass | 41696da4-dd43-45ae-b681-91644ca5a5dcgenid99172
</pre>
The logical definition for this class (in OBO format) is:
<pre>
intersection_of: PR:000027497 ! cytochrome c oxidase 7B
intersection_of: only_in_taxon NCBITaxon:10090 ! Mus musculus
</pre>

My understanding of equivalent classes is that I should expect another class in the ontology with that same logical definition. But, there isn't. In fact, in the whole ontology, there's only one term that is a child of PR:000027497, and that's the class that gave the error indicated above.

Looking at a few examples, I note that all of them have, in addition to the logical definition given above, union_of relationships. In the case given above:
<pre>
union_of: PR:P56393 ! cytochrome c oxidase subunit 7B, mitochondrial (mouse)
union_of: PR:Q9D2H1 ! cytochrome c oxidase subunit 7B2, mitochondrial (mouse)
</pre>

I've confirmed that the indicated term is the only one with such union statements so, again, I cannot find the issue.

**Comment by matentzn** [comment]
I fully agree with you @nataled 

I have been pleading this case for a while here: https://github.com/ontodev/robot/issues/733
If you could also comment there to move this forward, that would be great.

The test says: No two equivalentClass axioms for a term.  In 99% of the cases, this test is great - odds are two equivalent class axioms indicate an error. However, this case here, combining a logical definition with a union axiom, is exactly a corner case where the test should be less strict!
