### ISSUE TITLE
Genepio analysis had broken with "Failed to process ontology: failed_robot_base"

### ISSUE THREAD

**Issue by ddooley** [OBOFoundry/OBO-Dashboard#47]
I think this should perhaps be fixed now - I'm guessing it was triggered by capitalization error in import file paths that I have fixed now in github repo.  Can the analysis of genepio be triggered again to see if that fixed the problem?

**Comment by matentzn** [comment]
Looks ok to me now: http://dashboard.obofoundry.org/dashboard/index.html

@ddooley If you are happy, can you close?

**Comment by ddooley** [comment]
Yes, import file cleanup worked.  Thanks.
