### ISSUE TITLE
Some of the URI checks should change to "WARN" due to numeric-ness constraint?

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBO-Dashboard#51]
According to [FP3](http://obofoundry.org/principles/checks/fp_003), IDs should be purely numeric. This means that some of the ontologies like PR at least should get a yellow flag, as they make use of alphabetic characters. Or am I misreading something in the text of the principles?

**Comment by nataled** [comment]
So far as I can tell, that restriction shows up in the original formulation of the principle only in the Counter-Examples section, and within that section it appears to assume that alphanumeric local identifiers have semantic content. It is the semantic content aspect that seems most important. In any case, the restriction against alphanumerics was lifted many years ago (the principle text on the public page for some reason hasn't been updated; see #954 for new text and discussion thereof).

**Comment by matentzn** [comment]
Perfect, so this means we can close this :) thank you!
