### ISSUE TITLE
Change "open" heading to "explicitly open"

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBO-Dashboard#58]
@cmungall wrote (in email):
> For the dashboard headings can we say things like "explicitly open" rather than "open", The failures here are failures of declaration, it's not the case most of these are closed.

There may be other column labels that also need to be clarified like this.

**Comment by jamesaoverton** [comment]
I disagree. I think that the column headers should correspond to the names of the OBO Principles, which is the current design.

**Comment by matentzn** [comment]
I also disagree. Therefore, I will explicitly close this issue.
