### ISSUE TITLE
Dashboard checks entities that do not belong to ontology

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBO-Dashboard#60]
Right now, OBO Dashboard still checks stuff on entities that do not belong in it:

![image](https://user-images.githubusercontent.com/7070631/149779846-fc535e86-0768-466d-9649-ba5f29a294f9.png)

In the image, for example, ROBOT checks a GO term in RO.

**Comment by anitacaron** [comment]
This was fixed after using the base file or making one if unavailable.

**Comment by matentzn** [comment]
The robot report command itself takes a base iri parameter as well just FYI
