### ISSUE TITLE
Update dashboard

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBO-Dashboard#61]
I assume the dashboard (http://dashboard.obofoundry.org/dashboard/index.html) needs to be manually updated. It currently shows a version from 2021-11-22. Time for a refresh?

**Comment by matentzn** [comment]
Oops, I had started that process and left it over new year. Thanks for the reminder!

**Comment by matentzn** [comment]
Done http://dashboard.obofoundry.org/dashboard/index.html
