### ISSUE TITLE
Make the "users" dashboard item more tolerant to match our protocol

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBO-Dashboard#62]
From today's OBO Ops meeting:
> The only check that can be failing is Users, otherwise, all the tests shouldn’t be red (can be green, yellow or blue)

Rather than having this single exception to the requirement that new ontologies can't have any red cells in their dashboard, how about making the "users" cell yellow, rather than red/pink, if the ontology has no demonstrated users?

**Comment by matentzn** [comment]
This is discussed in great detail here:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1627

In a previous meeting, we decided _not_ do relax that check, as it reflects the OBO principles. We merely decided to relax it for new ontology requests.. So, I am generally against this. 

The only alternative would be to relax specifically the obo-nor board for the new requests, but that would take some hours of a developer to do. I think we are fine as is!

**Comment by nlharris** [comment]
Ok. I see that recent PR #1758 modified the text about dashboard requirements to:
> As of 4th May 2021, every new ontology submission is required to pass the [OBO Dashboard](http://dashboard.obofoundry.org/) quality control, which means that they are not allowed to have any substantial errors (anything "red"). The only exceptions to this requirement are (1) `Users`, and (2) results in the `Report` that pertain to terms from imported (external) ontologies.
