### ISSUE TITLE
Ensure that version IRIs actually resolve

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBO-Dashboard#67]
Right now, version IRIs are only checked for syntactic correctness.

**Comment by cthoyt** [comment]
Duplicate of https://github.com/OBOFoundry/OBO-Dashboard/issues/21 😅

**Comment by cthoyt** [comment]
Relevant code: 

https://github.com/OBOFoundry/OBO-Dashboard/blob/06b7dfbe99a37766217b5ecc5dacb4498a964199/util/dashboard/fp_004.py#L38-L67


will fix this myself
