### ISSUE TITLE
Follow redirects to homepage in FP 8

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBO-Dashboard#7]
@safisher points out that ORNASEQ's homepage resolves after a redirect:

https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1009#issuecomment-590848590

**Comment by beckyjackson** [comment]
The `requests` module should automatically follow redirects. Looking into this, this is an issue with the certificate.

Adding `verify=False` solves this, but could this be dangerous AND we get an `InsecureRequestWarning`.

We could do certificate verification: https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl
But I suspect we'd get an `SSLError` here.

**Comment by jamesaoverton** [comment]
Thanks @beckyjackson. What's the specific problem with the certificate?

**Comment by beckyjackson** [comment]
Here's the exception message:
```
HTTPSConnectionPool(host='kim.bio.upenn.edu', port=443): Max retries exceeded with url: /software/ornaseq.shtml (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

It passes with `verify=False`, but then I get the warning:
```
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

**Comment by jamesaoverton** [comment]
Thanks again @beckyjackson. It's weird that I don't see similar problems using other tools, such as cURL and Safari.

**Comment by jamesaoverton** [comment]
Thanks again @beckyjackson. It's weird that I don't see similar problems using other tools, such as cURL and Safari.

**Comment by matentzn** [comment]
@anitacaron during your next Dashboard revision, can you prioritise this?
