### ISSUE TITLE
Experiment: Swap in ELK 0.5

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBO-Dashboard#82]
For a [different problem](https://github.com/ontodev/robot/pull/999), we need to check if we can run the Dashboard with ELK 0.5 instead of ELK 0.4.3. To do this we have to:

1. Build a ROBOT jar from the branch here https://github.com/ontodev/robot/pull/999 (make sure its up to date with master)
2. Upload the jar file anywhere (even here in the Dashboard repo if need be, but I would prefer google drive or dropbox to not pollute the git history)
3. Build an ODK version locally which has that ROBOT jar in it (you have to change the ROBOT URL in the Dockerfile)
4. Run the Dashboard (if you cant run it, I can run it for you, but I will want to see the ODK branch with the changed ROBOT URL so I can build the ODK locally and then the branch of OBO Dashboard that refers to the right "odk tag").

**Comment by jamesaoverton** [comment]
Here is a pre-release with an attached JAR that should include ELK 0.5.0: https://github.com/ontodev/robot/releases/tag/v1.9.1-elk-0.5.0

**Comment by anitacaron** [comment]
We're already using ELK after some releases, and everything works fine.
