### ISSUE TITLE
Pipeline only works if there is one of each error types resulting from the ontologies in `dashboard-config.yml`

### ISSUE THREAD

**Issue by anitacaron** [OBOFoundry/OBO-Dashboard#85]
The pipeline expects at least 2-3 ontologies to be added.

EDIT: As a workaround, add

```
   - id: tmp
      mirror_from: "https://raw.githubusercontent.com/monarch-ebi-dev/robot_tests/master/custom-dashboard.owl"
```

as an ontology to your config.

**Comment by matentzn** [comment]
Correction: The pipeline expects at least one WARN, INFO, ERROR and PASS case in the corpus of tested ontologies.. Fixing this is high (not very high) priority to make the custom dashboard work more easily.

**Comment by anitacaron** [comment]
This issue has a simple fix: Check first which 'status' are available in the results instead of always using the four status types.

I enjoy this moment to create a template for the analysis page and the Python script to generate the plots and tables.
