### ISSUE TITLE
OBO Dashboard stopped working within reasonable time and memory constraints

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBO-Dashboard#87]
We have a bit of a problem; for some reason, we cannot run the OBO dashboard anymore; NCIT and friends of similar size stopped being processable. Before ROBOT 1.9.0, it was still possible to run OBO Dashboard with 48GB or memory, and a timeout of 2 hours per ontology. Now, we cannot run it at all anymore (not even with 55 GB memory and 4 hours timeout).

```
INFO:root:Creating dashboard for ncit...
INFO:root:RUNNING: make  ROBOT_JAR=/tools/robot.jar ROBOT=robot  dashboard/ncit/dashboard.html (Timeout: 14400)
Terminating process
```

Its the timeout that kicks in, not an out of memory error; but 4 hours is already a lot for an ontology.

I will try now with 56 GB memory which is the absolute maximum I have on my machine, and an 8 hour timeout.

Any ideas of how we can deal with this is very appreciated.

PS: my guess is the problem is ROBOT report, but it could also be ROBOT reason - I cannot see it in the log unfortunately.

**Comment by cthoyt** [comment]
I suggest skipping the big ones in he meantime. NCIT, NCBITaxon, and ChEBI aren't curated/created in a normal way anyway

**Comment by erik-whiting** [comment]
@matentzn is this reproducible by running `make ncit` or something similar locally?

**Comment by erik-whiting** [comment]
Also, what's the impact? http://dashboard.obofoundry.org/dashboard/index.html looks fine?

**Comment by erik-whiting** [comment]
Also, ROBOT 1.9.1 added the code in [this PR](https://github.com/ontodev/robot/pull/1018), some of the comments mention a performance hit. I wonder if that's why you're experiencing problems

**Comment by matentzn** [comment]
Yea, it failed again, with the increased memory and time constraints.

**Comment by matentzn** [comment]
@erik-whiting we cannot re-run it at the moment (update)
