### ISSUE TITLE
Bug in display of info count

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBO-Dashboard#92]
It appears the format string for info messages in the ROBOT report column doesn't get filled properly

<img width="1174" alt="Screenshot 2023-06-30 at 11 11 55" src="https://github.com/OBOFoundry/OBO-Dashboard/assets/5069736/4cfe8a15-c3b6-4907-8896-1679ea8ecd1c">

**Comment by anitacaron** [comment]
Same as https://github.com/OBOFoundry/OBO-Dashboard/issues/32
